/**
 * Global Variables
 */
const PROJECT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_ID = 'XXXXXXXXXXXXXXXXXX';
const OAUTH_CLIENT_SECRET = 'XXXXXXXXXXXXXXXXXX';
const DOWNSTAIRS_THERMOSTAT = 'XXXXXXXXXXXXXXXXXX';
const UPSTAIRS_THERMOSTAT = 'XXXXXXXXXXXXXXXXXX';